# Settings for the app
app:
  # HTML Title
  title: Miami Baywalk
  # Header name
  name: Miami Baywalk
  # Meta description that will show up in Google search results
  meta_description: _(Show us where and what you would do to activate the Miami Baywalk)
  # Meta author that will show up in Google search results
  meta_author: PoePublic.org


  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  # list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false

  geocoding_enabled: false
  geocode_field_label: _(Enter an address...)
  geocode_bounding_box: [39.830159, -75.478821, 40.167331, -74.781189]  # top, left, bottom, right

  options:
    center:
      lat: 25.779
      lng: -80.189
    zoom: 15
    minZoom: 14
    maxZoom: 18
  layers:
    # Raster Tile Layers
    # ==================
    # - url: https://api.tiles.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6IjZjNmRjNzk3ZmE2MTcwOTEwMGY0MzU3YjUzOWFmNWZhIn0.Y8bhBaUMqFiPrDRW9hieoQ
    #   attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>. Geocoding Courtesy of <a href="http://www.mapquest.com/" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png">.'
    - url: https://api.mapbox.com/styles/v1/miamidda/cj65359pq5v6i2qrzfiy22rzt/tiles/256/{z}/{x}/{y}?access_token=pk.eyJ1IjoibWlhbWlkZGEiLCJhIjoiY2o1M3JzY3F2MGIzNTJ6bTRxaWQ4YjJ5diJ9.WOldxum-Cfr7SHigaEwPiQ

    # Mapbox GL Layers
    # ================
    # - type: mapbox
    #   style: mapbox://styles/miamidda/cj56r3vad3dqn2ro33d046f5m
    #   accessToken: pk.eyJ1IjoibWlhbWlkZGEiLCJhIjoiY2o1M3JzY3F2MGIzNTJ6bTRxaWQ4YjJ5diJ9.WOldxum-Cfr7SHigaEwPiQ

    # GeoJSON Layers
    # ==============
    # - url: /static/data/philadelphia.geojson
    #   type: json
    #   rules:
    #     - condition: 'true'
    #       style:
    #         color: "#444"
    #         opacity: 0.6
    #         fillOpacity: 0.1
    #         weight: 1

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).

# - Display as circles (vectors) when zoomed out
# - Display as small icons when zoomed in
# - Display as large icons when focused

place_types:
  education:
    label: _(Education)
    rules:
      - condition: '"{{location_type}}" === "education" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        style:
          color: '#EEB768'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "education" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/education-01.png
          iconSize: [19, 19]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "education" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/education-01.png
          # shadowUrl: /static/css/images/circle-shadow.png
          iconSize: [39, 39]
          # shadowSize: [37, 37]
          iconAnchor: [20, 20]

  entertainment:
    label: _(Entertainment)
    rules:
      - condition: '"{{location_type}}" === "entertainment" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        style:
          color: '#BCBDC7'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "entertainment" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/entertainment-01.png
          iconSize: [19, 19]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "entertainment" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/entertainment-01.png
          # shadowUrl: /static/css/images/circle-shadow.png
          iconSize: [39, 39]
          # shadowSize: [37, 37]
          iconAnchor: [20, 20]

  engagement:
    label: _(Engagement/Advocacy)
    rules:
      - condition: '"{{location_type}}" === "engagement" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        style:
          color: '#70C8B6'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "engagement" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/engagement-01.png
          iconSize: [19, 19]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "engagement" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/engagement-01.png
          # shadowUrl: /static/css/images/circle-shadow.png
          iconSize: [39, 39]
          # shadowSize: [37, 37]
          iconAnchor: [20, 20]

  culture:
    label: _(Arts/Culture)
    rules:
      - condition: '"{{location_type}}" === "culture" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        style:
          color: '#F1626B'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "culture" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/culture-01.png
          iconSize: [19, 19]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "culture" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/culture-01.png
          # shadowUrl: /static/css/images/circle-shadow.png
          iconSize: [39, 39]
          # shadowSize: [37, 37]
          iconAnchor: [20, 20]

  wellness:
    label: _(Health/Wellness)
    rules:
      - condition: '"{{location_type}}" === "wellness" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        style:
          color: '#D2E281'
          radius: 3
          weight: 1
          opacity: 0.9
          fillOpacity: 1

      - condition: '"{{location_type}}" === "wellness" && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/wellness-01.png
          iconSize: [19, 19]
          iconAnchor: [10, 10]

      - condition: '"{{location_type}}" === "wellness" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/wellness-01.png
          # shadowUrl: /static/css/images/circle-shadow.png
          iconSize: [39, 39]
          # shadowSize: [37, 37]
          iconAnchor: [20, 20]


activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported:
    from: '2017-07-28 00:00 -0500'   # Daylight savings begins mid-March
    until: '2017-11-01 00:00 -0400'  # and ends mid-October.
  add_button_label: _(Add a Place)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(List All Ideas)
  show_map_button_label: _(Show the Map)
  action_text: _(added)
  title: _(Tell us more...)
  action_text: _(created)
  anonymous_name: _(Someone)
  submit_button_label: _(Submit)

  location_item_name: idea

  items:
    - prompt: _(What is the title of your idea?)
      name: title
      type: text
      attrs:
        - key: size
          value: 100

    - prompt: _(What kind of activation is it?)
      type: radiogroup
      options:
        - label: _(Education)
          value: education
        - label: _(Entertainment)
          value: entertainment
        - label: _(Engagement/Advocacy)
          value: engagement
        - label: _(Arts/Culture)
          value: culture
        - label: _(Health/Wellness)
          value: wellness
      name: location_type
      attrs:
        - key: required

    - prompt: _(What’s your big idea?)
      name: intent
      type: textarea
      attrs:
        - key: maxlength
          value: 750

    - prompt: _(What’s the purpose?)
      name: intent
      type: textarea
      attrs:
        - key: placeholder
          value: _(So I can...)
        - key: maxlength
          value: 100

    - prompt: _(How do you define success?)
      name: success
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(Who is your audience?)
      name: audience
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(Who will help you market/promote this event?)
      name: promoters
      type: textarea
      attrs:
        - key: maxlength
          value: 750

    - prompt: _(Who do you need to work with to make this happen? Who are your partners and/or sponsors?)
      name: partners
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(What is your timeline for implementation?  When would your events be held?)
      name: timeline
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(What is your budget? Grant requests will be limited to $5,000 and below.)
      help_text: _(Please specify your anticipated expenses by line item.)
      name: budget
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(How will your proposal help grow awareness about Baywalk?)
      name: growing_awareness
      type: textarea
      attrs:
        - key: maxlength
          value: 100

    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true
      attrs:
        - key: placeholder
          value: _(Name)

    - prompt: _(Organization)
      type: text
      name: private-organization
      optional: true
      attrs:
        - key: placeholder
          value: _(Organization)

    - prompt: _(Your Email)
      type: email
      name: private-submitter_email
      sticky: true
      attrs:
        - key: placeholder
          value: _(Email address)

    - prompt: _(Phone Number)
      type: tel
      name: private-submitter_phone

survey:
  submission_type: comments
  adding_supported: true

  # Response config
  show_responses: true
  # Set to true if the user should only submit a survey once
  single_submission: false
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Yes or no question)
      type: radiogroup
      options:
        - label: _(Indeed)
          value: yeah
        - label: _(I don't think so)
          value: nah
      name: y_or_n
      attrs:
        - key: required
    - prompt: _(All that apply questiion)
      type: checkboxgroup
      options:
        - label: _(First)
          value: option1
        - label: _(Second)
          value: option2
        - label: _(Third)
          value: option3
        - label: _(Fourth)
          value: option4
      name: all_that_apply
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      sticky: true

support:
  submission_type: support
  adding_supported: true
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    start_page: true

  - title: Filter Places
    slug: filter-type
    pages:
      - title: All
        external: true
        url: /filter/all
      - title: _(Education)
        url: /filter/education
        external: true
      - title: _(Entertainment)
        url: /filter/entertainment
        external: true
      - title: _(Engagement/Advocacy)
        url: /filter/engagement
        external: true
      - title: _(Arts/Culture)
        url: /filter/culture
        external: true
      - title: _(Health/Wellness)
        url: /filter/wellness
        external: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email